"""The vendored Sequence Coordinates feature-type catalog (src/rcsb_mcp/feature_types.py).

rcsb_seqcoord_annotations filters on a feature TYPE. The filter is case-sensitive and an
unknown name silently matches nothing, and only some sources carry a given type (ACTIVE_SITE:
UniProt only), so the vocabulary comes from the Sequence Coordinates schema and each type's
sources from the Data API fields that vocabulary is built from, both generated by
scripts/generate_feature_types.py. These tests pin the vendored catalog, its agreement with
the tool's sources, and the generator's rules on made-up data. No network.
"""

import importlib.util
import pathlib
import pytest

from rcsb_mcp import feature_types as ft
from rcsb_mcp.queries import ANNOTATION_SOURCES

_SCRIPT = pathlib.Path(__file__).resolve().parents[1] / "scripts" / "generate_feature_types.py"
_spec = importlib.util.spec_from_file_location("generate_feature_types", _SCRIPT)
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)


def test_the_vocabulary_is_sorted_unique_and_carries_the_unguessable_names():
    assert ft.FEATURE_TYPES == sorted(set(ft.FEATURE_TYPES))
    # names an agent could not spell from the concept -- the reason the list is vendored
    for name in ("ACTIVE_SITE", "CIS_PEPTIDE", "SCOP_2_B_SUPERFAMILY", "TURN_TY_1_P",
                 "MA_QA_METRIC_LOCAL_TYPE_PLDDT"):
        assert name in ft.FEATURE_TYPES, name


def test_the_generator_knows_the_same_sources_as_the_tool():
    assert gen.SOURCES == list(ANNOTATION_SOURCES)
    assert {source for _, _, source in gen.TYPE_FIELDS} == set(gen.SOURCES)


def test_every_type_has_its_sources_in_order_and_only_known_ones_have_none():
    assert list(ft.FEATURE_TYPE_SOURCES) == ft.FEATURE_TYPES
    for t, sources in ft.FEATURE_TYPE_SOURCES.items():
        assert sources == [s for s in gen.SOURCES if s in sources], f"{t}: {sources} out of order"
        assert sources or t in gen.KNOWN_UNTRACED or t in gen.NOT_SERVED, f"{t} has no source"


def test_the_map_records_where_each_kind_of_feature_lives():
    """Asking the wrong source returns nothing: a session asked PDB_ENTITY for ACTIVE_SITE."""
    assert ft.FEATURE_TYPE_SOURCES["ACTIVE_SITE"] == ["UNIPROT"]
    assert ft.FEATURE_TYPE_SOURCES["HYDROPATHY"] == ["PDB_ENTITY"]
    assert ft.FEATURE_TYPE_SOURCES["CATH"] == ["PDB_INSTANCE"]
    assert ft.FEATURE_TYPE_SOURCES["DISULFIDE_BRIDGE"] == ["PDB_INSTANCE"]  # struct_conn
    assert ft.FEATURE_TYPE_SOURCES["ASA_BOUND"] == ["PDB_INTERFACE"]
    assert ft.FEATURE_TYPE_SOURCES["BINDING_SITE"] == ["UNIPROT", "PDB_INSTANCE"]


@pytest.mark.parametrize("value, name", [
    ("hydropathy", "HYDROPATHY"),
    ("disulfide bridge", "DISULFIDE_BRIDGE"),
    ("CIS-PEPTIDE", "CIS_PEPTIDE"),
    ("SCOP2B_SUPERFAMILY", "SCOP_2_B_SUPERFAMILY"),
    ("TURN_TY1_P", "TURN_TY_1_P"),
    ("AMPylation", "AM_PYLATION"),
    ("cGMPylation", "C_GM_PYLATION"),
    ("Chromophore/chromophore-like", "CHROMOPHORE_CHROMOPHORE_LIKE"),
    ("4-Phosphopantetheine", "_4_PHOSPHOPANTETHEINE"),
    ("MA_QA_METRIC_LOCAL_TYPE_PLDDT_[0,1]", "MA_QA_METRIC_LOCAL_TYPE_PLDDT_0_1"),
    ("(3R)-3-Hydroxybutyrylation", "_3_R_3_HYDROXYBUTYRYLATION"),
    ("(3-Aminopropyl)(5'-adenosyl)phosphono amidation", "_3_AMINOPROPYL_5_ADENOSYL_PHOSPHONO_AMIDATION"),
])
def test_data_api_values_become_featurestype_names(value, name):
    """Pairs from the live schemas (2026-10-09), one per rule of enum_name."""
    assert gen.enum_name(value) == name


def test_allowed_values_are_read_from_the_field_description():
    assert gen.allowed_values("The connection type.  Allowable values: covalent bond, "
                              "disulfide bridge, 2,3-Dicarboxypropylation", "x") == [
        "covalent bond", "disulfide bridge", "2,3-Dicarboxypropylation"]
    with pytest.raises(RuntimeError, match="no allowable values"):
        gen.allowed_values("A type or category of the feature.", "x")


def test_type_sources_traces_every_name_to_the_fields_that_list_it(monkeypatch):
    monkeypatch.setattr(gen, "KNOWN_UNTRACED", {"PROTEIN_BINDING": "made up"})
    fields = [("UNIPROT", ["ACTIVE_SITE", "BINDING_SITE"]),
              ("PDB_INSTANCE", ["BINDING_SITE", "disulfide bridge"]),
              ("PDB_INSTANCE", ["Disulfide bridge", "Phosphorylation"])]  # later case twin takes "_"
    types = ["ACTIVE_SITE", "BINDING_SITE", "DISULFIDE_BRIDGE", "DISULFIDE_BRIDGE_", "PROTEIN_BINDING"]
    sources, strays, spellings = gen.type_sources(types, fields)
    assert sources == {"ACTIVE_SITE": ["UNIPROT"], "BINDING_SITE": ["UNIPROT", "PDB_INSTANCE"],
                       "DISULFIDE_BRIDGE": ["PDB_INSTANCE"], "DISULFIDE_BRIDGE_": ["PDB_INSTANCE"],
                       "PROTEIN_BINDING": []}
    assert strays == ["PHOSPHORYLATION"]  # a Data API value Sequence Coordinates does not list yet
    # the stored spelling a filter must use, wherever it is not the name; twins share one
    assert spellings == {"DISULFIDE_BRIDGE": "DISULFIDE BRIDGE", "DISULFIDE_BRIDGE_": "DISULFIDE BRIDGE"}


def test_case_twins_from_two_sources_stop_the_generator():
    """Which twin keeps the plain name follows the TYPE_FIELDS order; across two sources that
    order alone would decide a type's sources, so it is refused rather than guessed."""
    with pytest.raises(RuntimeError, match="DISULFIDE_BRIDGE"):
        gen.type_sources(["DISULFIDE_BRIDGE", "DISULFIDE_BRIDGE_"],
                         [("UNIPROT", ["Disulfide Bridge"]), ("PDB_INSTANCE", ["disulfide bridge"])])


def test_the_vocabulary_is_the_union_of_every_introspection(monkeypatch):
    """During a rollout pods answer with different schemas; the newer names must survive a run
    that also reaches an older pod, and the split must be visible."""
    calls = [["ACTIVE_SITE"]] * gen.INTROSPECTIONS
    calls[1] = ["ACTIVE_SITE", "PHOSPHORYLATION"]  # one newer pod, neither first nor last
    answers = iter(calls)
    monkeypatch.setattr(gen.time, "sleep", lambda _: None)
    monkeypatch.setattr(gen, "_post", lambda url, query, what: {
        "__type": {"enumValues": [{"name": n} for n in next(answers)]}})
    types, sizes = gen.feature_types()
    assert gen.INTROSPECTIONS > 1
    assert types == ["ACTIVE_SITE", "PHOSPHORYLATION"]
    assert sizes == [len(c) for c in calls]


def test_a_featurestype_name_nothing_traces_to_stops_the_generator():
    """How a broken naming rule shows up: the name it should have produced is left untraced."""
    with pytest.raises(RuntimeError, match="CIS_PEPTIDE"):
        gen.type_sources(["CIS_PEPTIDE"], [("PDB_INSTANCE", ["CIS PEPTIDE_X"])])


def test_a_type_sequence_coordinates_does_not_serve_has_no_source(monkeypatch):
    """A field lists it, yet asking for it can only come back empty (UNASSIGNED_SEC_STRUCT)."""
    assert ft.FEATURE_TYPE_SOURCES["UNASSIGNED_SEC_STRUCT"] == []
    monkeypatch.setattr(gen, "NOT_SERVED", {"CATH": "made up"})
    sources, _, _ = gen.type_sources(["CATH", "SHEET"], [("PDB_INSTANCE", ["CATH", "SHEET"])])
    assert sources == {"CATH": [], "SHEET": ["PDB_INSTANCE"]}


def test_every_type_with_a_field_is_filed_under_it_and_only_there():
    by_field = ft.FEATURE_TYPES_BY_FIELD
    assert list(by_field) == [f"{root}.{path}" for root, path, _ in gen.TYPE_FIELDS]
    filed = {t for names in by_field.values() for t in names}
    assert filed == set(ft.FEATURE_TYPES) - set(gen.KNOWN_UNTRACED)
    assert "BINDING_SITE" in by_field["uniprot.rcsb_uniprot_feature.type"]
    assert "BINDING_SITE" in by_field["polymer_entity_instance.rcsb_polymer_instance_feature.type"]
    assert "DISULFIDE_BRIDGE" in by_field["polymer_entity_instance.rcsb_polymer_struct_conn.connect_type"]
    assert "DISULFIDE_BRIDGE_" in by_field["polymer_entity_instance.pdbx_modification_feature.category"]


def test_types_are_filed_under_every_field_listing_them_and_twins_apart(monkeypatch):
    monkeypatch.setattr(gen, "TYPE_FIELDS", [("u", "f.type", "UNIPROT"), ("i", "f.type", "PDB_INSTANCE"),
                                             ("i", "c.connect_type", "PDB_INSTANCE"),
                                             ("i", "m.category", "PDB_INSTANCE")])
    fields = [("UNIPROT", ["BINDING_SITE"]), ("PDB_INSTANCE", ["BINDING_SITE", "CATH"]),
              ("PDB_INSTANCE", ["disulfide bridge"]), ("PDB_INSTANCE", ["Disulfide bridge"])]
    types = ["BINDING_SITE", "CATH", "DISULFIDE_BRIDGE", "DISULFIDE_BRIDGE_"]
    assert gen.types_by_field(types, fields) == {
        "u.f.type": ["BINDING_SITE"],
        "i.f.type": ["BINDING_SITE", "CATH"],
        "i.c.connect_type": ["DISULFIDE_BRIDGE"],      # the earlier twin keeps the plain name
        "i.m.category": ["DISULFIDE_BRIDGE_"],
    }


def test_the_filter_spelling_is_recorded_wherever_it_is_not_the_name():
    """Measured 2026-10-09: each name finds 0 features, its stored spelling the ones the API
    returns under the name (1CRN_1 3, 6VXX_1 48, 1HZH_1 6, 4HHB_1 2)."""
    spelling = ft.FEATURE_TYPE_FILTER_SPELLING
    assert spelling["DISULFIDE_BRIDGE"] == "DISULFIDE BRIDGE"
    assert spelling["COVALENT_BOND"] == "COVALENT BOND"
    assert spelling["CIS_PEPTIDE"] == "CIS-PEPTIDE"
    assert spelling["SCOP_2_B_SUPERFAMILY"] == "SCOP2B_SUPERFAMILY"
    assert "ACTIVE_SITE" not in spelling and "HYDROPATHY" not in spelling  # same either way
    assert set(spelling) <= set(ft.FEATURE_TYPES)
    assert all(v != k and v == v.upper() for k, v in spelling.items())


def test_the_vendored_module_is_exactly_what_the_generator_renders():
    """Re-rendering the committed data reproduces the file, comments included; whether the data
    still matches the live APIs is what `generate_feature_types.py --check` answers."""
    assert pathlib.Path(ft.__file__).read_text() == gen.render_module(
        ft.FEATURE_TYPES, ft.FEATURE_TYPE_SOURCES, ft.FEATURE_TYPE_FILTER_SPELLING,
        ft.FEATURE_TYPES_BY_FIELD)
