"""Scope (granularity) of every searchable RCSB attribute.

Auto-generated by scripts/generate_attribute_scopes.py from the Data API GraphQL
schema plus the vendored attribute catalogs. Do not edit by hand.

The maps are keyed by the attribute's ROOT path segment, which is what determines
the object it hangs off; `queries.scope_of` does the lookup and applies the
entry-constant overrides below. Kept per catalog because `rcsb_id` denotes the
entity container in the structure schema and the chemical definition in the
chemical one.
"""

from rcsb_mcp.attribute_types import AttributeScope

# structure: 148 roots covering 675 attributes.
SEARCH_ATTRIBUTE_SCOPES: dict[str, AttributeScope] = {
    "audit_author": "entry",
    "cell": "entry",
    "chem_comp": "mol_definition",
    "citation": "entry",
    "database_2": "entry",
    "diffrn": "entry",
    "diffrn_detector": "entry",
    "diffrn_radiation": "entry",
    "diffrn_source": "entry",
    "drugbank_container_identifiers": "mol_definition",
    "drugbank_info": "mol_definition",
    "drugbank_target": "mol_definition",
    "em_2d_crystal_entity": "entry",
    "em_3d_crystal_entity": "entry",
    "em_3d_fitting": "entry",
    "em_3d_fitting_list": "entry",
    "em_3d_reconstruction": "entry",
    "em_ctf_correction": "entry",
    "em_diffraction": "entry",
    "em_diffraction_shell": "entry",
    "em_diffraction_stats": "entry",
    "em_embedding": "entry",
    "em_entity_assembly": "entry",
    "em_experiment": "entry",
    "em_helical_entity": "entry",
    "em_image_recording": "entry",
    "em_imaging": "entry",
    "em_particle_selection": "entry",
    "em_single_particle_entity": "entry",
    "em_software": "entry",
    "em_specimen": "entry",
    "em_staining": "entry",
    "em_vitrification": "entry",
    "entity_poly": "polymer_entity",
    "entity_src_gen": "polymer_entity",
    "entity_src_nat": "polymer_entity",
    "exptl": "entry",
    "exptl_crystal": "entry",
    "exptl_crystal_grow": "entry",
    "ihm_entry_collection_mapping": "entry",
    "pdbx_SG_project": "entry",
    "pdbx_audit_support": "entry",
    "pdbx_database_PDB_obs_spr": "entry",
    "pdbx_database_related": "entry",
    "pdbx_database_status": "entry",
    "pdbx_deposit_group": "entry",
    "pdbx_entity_branch": "branched_entity",
    "pdbx_entity_branch_descriptor": "branched_entity",
    "pdbx_entity_nonpoly": "non_polymer_entity",
    "pdbx_initial_refinement_model": "entry",
    "pdbx_molecule_features": "entry",
    "pdbx_nmr_details": "entry",
    "pdbx_nmr_refine": "entry",
    "pdbx_nmr_sample_details": "entry",
    "pdbx_nmr_software": "entry",
    "pdbx_nmr_spectrometer": "entry",
    "pdbx_reference_molecule": "mol_definition",
    "pdbx_reference_molecule_family": "mol_definition",
    "pdbx_reference_molecule_related_structures": "mol_definition",
    "pdbx_reference_molecule_synonyms": "mol_definition",
    "pdbx_reflns_twin": "entry",
    "pdbx_serial_crystallography_measurement": "entry",
    "pdbx_serial_crystallography_sample_delivery": "entry",
    "pdbx_serial_crystallography_sample_delivery_fixed_target": "entry",
    "pdbx_serial_crystallography_sample_delivery_injection": "entry",
    "pdbx_soln_scatter": "entry",
    "pdbx_soln_scatter_model": "entry",
    "pdbx_struct_assembly": "assembly",
    "pdbx_struct_assembly_auth_evidence": "assembly",
    "pdbx_vrpt_summary_em": "entry",
    "pdbx_vrpt_summary_entity_fit_to_map": "polymer_instance",
    "pdbx_vrpt_summary_geometry": "entry",
    "rcsb_accession_info": "entry",
    "rcsb_assembly_annotation": "assembly",
    "rcsb_assembly_container_identifiers": "assembly",
    "rcsb_assembly_info": "assembly",
    "rcsb_binding_affinity": "entry",
    "rcsb_branched_entity": "branched_entity",
    "rcsb_branched_entity_annotation": "branched_entity",
    "rcsb_branched_entity_container_identifiers": "branched_entity",
    "rcsb_branched_entity_feature_summary": "branched_entity",
    "rcsb_branched_entity_instance_container_identifiers": "branched_instance",
    "rcsb_branched_entity_keywords": "branched_entity",
    "rcsb_branched_entity_name_com": "branched_entity",
    "rcsb_branched_entity_name_sys": "branched_entity",
    "rcsb_branched_instance_annotation": "branched_instance",
    "rcsb_branched_instance_feature_summary": "branched_instance",
    "rcsb_chem_comp_annotation": "mol_definition",
    "rcsb_chem_comp_container_identifiers": "mol_definition",
    "rcsb_chem_comp_descriptor": "mol_definition",
    "rcsb_chem_comp_info": "mol_definition",
    "rcsb_chem_comp_related": "mol_definition",
    "rcsb_chem_comp_synonyms": "mol_definition",
    "rcsb_chem_comp_target": "mol_definition",
    "rcsb_comp_model_provenance": "entry",
    "rcsb_entity_host_organism": "polymer_entity",
    "rcsb_entity_source_organism": "polymer_entity",
    "rcsb_entry_container_identifiers": "entry",
    "rcsb_entry_group_membership": "entry",
    "rcsb_entry_info": "entry",
    "rcsb_external_references": "entry",
    "rcsb_genomic_lineage": "polymer_entity",
    "rcsb_id": "entry",
    "rcsb_ihm_dataset_list": "entry",
    "rcsb_ihm_dataset_source_db_reference": "entry",
    "rcsb_ligand_neighbors": "polymer_instance",
    "rcsb_ma_qa_metric_global": "entry",
    "rcsb_membrane_lineage": "polymer_entity",
    "rcsb_nonpolymer_entity": "non_polymer_entity",
    "rcsb_nonpolymer_entity_annotation": "non_polymer_entity",
    "rcsb_nonpolymer_entity_container_identifiers": "non_polymer_entity",
    "rcsb_nonpolymer_entity_feature": "non_polymer_entity",
    "rcsb_nonpolymer_entity_feature_summary": "non_polymer_entity",
    "rcsb_nonpolymer_entity_instance_container_identifiers": "non_polymer_instance",
    "rcsb_nonpolymer_entity_keywords": "non_polymer_entity",
    "rcsb_nonpolymer_entity_name_com": "non_polymer_entity",
    "rcsb_nonpolymer_instance_annotation": "non_polymer_instance",
    "rcsb_nonpolymer_instance_validation_score": "non_polymer_instance",
    "rcsb_polymer_entity": "polymer_entity",
    "rcsb_polymer_entity_annotation": "polymer_entity",
    "rcsb_polymer_entity_container_identifiers": "polymer_entity",
    "rcsb_polymer_entity_feature_summary": "polymer_entity",
    "rcsb_polymer_entity_group_membership": "polymer_entity",
    "rcsb_polymer_entity_instance_container_identifiers": "polymer_instance",
    "rcsb_polymer_entity_keywords": "polymer_entity",
    "rcsb_polymer_entity_name_com": "polymer_entity",
    "rcsb_polymer_entity_name_sys": "polymer_entity",
    "rcsb_polymer_instance_annotation": "polymer_instance",
    "rcsb_polymer_instance_feature_summary": "polymer_instance",
    "rcsb_polymer_struct_conn": "polymer_instance",
    "rcsb_primary_citation": "entry",
    "rcsb_pubmed_abstract_text": "entry",
    "rcsb_pubmed_container_identifiers": "entry",
    "rcsb_pubmed_mesh_descriptors_lineage": "entry",
    "rcsb_repository_holdings_current": "entry",
    "rcsb_struct_symmetry": "assembly",
    "rcsb_struct_symmetry_lineage": "assembly",
    "rcsb_target_neighbors": "non_polymer_instance",
    "rcsb_uniprot_annotation": "polymer_entity",
    "rcsb_uniprot_container_identifiers": "polymer_entity",
    "rcsb_uniprot_external_reference": "polymer_entity",
    "rcsb_uniprot_protein": "polymer_entity",
    "refine": "entry",
    "reflns": "entry",
    "software": "entry",
    "struct": "entry",
    "struct_keywords": "entry",
    "symmetry": "entry"
}

# Roots the Data API exposes at more than one granularity, collapsed above to
# the COARSEST — the direction that can only make the split detector quieter.
# Recorded so the collapse is visible rather than buried in the map.
SEARCH_ATTRIBUTE_AMBIGUOUS_ROOTS: dict[str, list[AttributeScope]] = {
    "pdbx_vrpt_summary_entity_fit_to_map": [
        "non_polymer_instance",
        "polymer_instance"
    ],
    "rcsb_id": [
        "assembly",
        "branched_entity",
        "branched_instance",
        "entry",
        "mol_definition",
        "non_polymer_entity",
        "non_polymer_instance",
        "polymer_entity",
        "polymer_instance"
    ],
    "rcsb_ligand_neighbors": [
        "branched_instance",
        "polymer_instance"
    ]
}

# Attributes filed under a finer root whose VALUE is the parent entry's id, so it
# is identical across every sibling and two conditions on it can never be met by
# different siblings. `queries.scope_of` returns "entry" for these.
SEARCH_ATTRIBUTE_ENTRY_CONSTANT: list[str] = [
    "rcsb_assembly_container_identifiers.entry_id",
    "rcsb_branched_entity_container_identifiers.entry_id",
    "rcsb_branched_entity_instance_container_identifiers.entry_id",
    "rcsb_comp_model_provenance.entry_id",
    "rcsb_entry_container_identifiers.entry_id",
    "rcsb_nonpolymer_entity_instance_container_identifiers.entry_id",
    "rcsb_polymer_entity_container_identifiers.entry_id",
    "rcsb_polymer_entity_instance_container_identifiers.entry_id"
]

# Roots holding MANY records per object (103 of 148).
# Two conditions on one of these can land on DIFFERENT records of the SAME object, so
# scope equality does not mean the conditions co-occur — software.name and
# software.classification are both entry-scoped, yet 18 of 25 sampled hits for
# AND(name~PHENIX, classification~'data reduction') have no single record with both.
SEARCH_ATTRIBUTE_REPEATING_ROOTS: list[str] = [
    "audit_author",
    "citation",
    "database_2",
    "diffrn",
    "diffrn_detector",
    "diffrn_radiation",
    "diffrn_source",
    "drugbank_target",
    "em_2d_crystal_entity",
    "em_3d_crystal_entity",
    "em_3d_fitting",
    "em_3d_fitting_list",
    "em_3d_reconstruction",
    "em_ctf_correction",
    "em_diffraction",
    "em_diffraction_shell",
    "em_diffraction_stats",
    "em_embedding",
    "em_entity_assembly",
    "em_helical_entity",
    "em_image_recording",
    "em_imaging",
    "em_particle_selection",
    "em_single_particle_entity",
    "em_software",
    "em_specimen",
    "em_staining",
    "em_vitrification",
    "entity_src_gen",
    "entity_src_nat",
    "exptl",
    "exptl_crystal",
    "exptl_crystal_grow",
    "ihm_entry_collection_mapping",
    "pdbx_SG_project",
    "pdbx_audit_support",
    "pdbx_database_PDB_obs_spr",
    "pdbx_database_related",
    "pdbx_deposit_group",
    "pdbx_entity_branch_descriptor",
    "pdbx_initial_refinement_model",
    "pdbx_molecule_features",
    "pdbx_nmr_refine",
    "pdbx_nmr_sample_details",
    "pdbx_nmr_software",
    "pdbx_nmr_spectrometer",
    "pdbx_reference_molecule_related_structures",
    "pdbx_reference_molecule_synonyms",
    "pdbx_reflns_twin",
    "pdbx_serial_crystallography_measurement",
    "pdbx_serial_crystallography_sample_delivery",
    "pdbx_serial_crystallography_sample_delivery_fixed_target",
    "pdbx_serial_crystallography_sample_delivery_injection",
    "pdbx_soln_scatter",
    "pdbx_soln_scatter_model",
    "pdbx_struct_assembly_auth_evidence",
    "pdbx_vrpt_summary_em",
    "pdbx_vrpt_summary_entity_fit_to_map",
    "pdbx_vrpt_summary_geometry",
    "rcsb_assembly_annotation",
    "rcsb_binding_affinity",
    "rcsb_branched_entity_annotation",
    "rcsb_branched_entity_feature_summary",
    "rcsb_branched_entity_name_sys",
    "rcsb_branched_instance_annotation",
    "rcsb_branched_instance_feature_summary",
    "rcsb_chem_comp_annotation",
    "rcsb_chem_comp_related",
    "rcsb_chem_comp_synonyms",
    "rcsb_chem_comp_target",
    "rcsb_entity_host_organism",
    "rcsb_entity_source_organism",
    "rcsb_entry_group_membership",
    "rcsb_external_references",
    "rcsb_genomic_lineage",
    "rcsb_ihm_dataset_list",
    "rcsb_ihm_dataset_source_db_reference",
    "rcsb_ligand_neighbors",
    "rcsb_ma_qa_metric_global",
    "rcsb_membrane_lineage",
    "rcsb_nonpolymer_entity_annotation",
    "rcsb_nonpolymer_entity_feature",
    "rcsb_nonpolymer_entity_feature_summary",
    "rcsb_nonpolymer_entity_name_com",
    "rcsb_nonpolymer_instance_annotation",
    "rcsb_nonpolymer_instance_validation_score",
    "rcsb_polymer_entity_annotation",
    "rcsb_polymer_entity_feature_summary",
    "rcsb_polymer_entity_group_membership",
    "rcsb_polymer_entity_name_com",
    "rcsb_polymer_entity_name_sys",
    "rcsb_polymer_instance_annotation",
    "rcsb_polymer_instance_feature_summary",
    "rcsb_polymer_struct_conn",
    "rcsb_pubmed_mesh_descriptors_lineage",
    "rcsb_struct_symmetry",
    "rcsb_struct_symmetry_lineage",
    "rcsb_target_neighbors",
    "rcsb_uniprot_annotation",
    "rcsb_uniprot_external_reference",
    "refine",
    "reflns",
    "software"
]

# The PATHS the Search API nested-indexes (41): it tracks the record, so
# conditions kept together in their OWN group are required to hold on one record.
# That makes these fixable at the query level; the rest of the repeating roots are not.
# Paths, not roots: the flag sits on the coherent sub-object, which for 6 roots is a
# descendant (rcsb_uniprot_container_identifiers.reference_sequence_identifiers, ...),
# so an attribute is coherent-able only when it sits UNDER one of these prefixes.
SEARCH_ATTRIBUTE_NESTED_ROOTS: list[str] = [
    "citation",
    "drugbank_info.drug_products",
    "pdbx_database_related",
    "pdbx_entity_branch_descriptor",
    "pdbx_initial_refinement_model",
    "rcsb_assembly_annotation",
    "rcsb_binding_affinity",
    "rcsb_branched_entity_annotation",
    "rcsb_branched_entity_annotation.annotation_lineage",
    "rcsb_branched_entity_container_identifiers.reference_identifiers",
    "rcsb_branched_entity_feature_summary",
    "rcsb_branched_instance_annotation",
    "rcsb_branched_instance_annotation.annotation_lineage",
    "rcsb_branched_instance_feature_summary",
    "rcsb_chem_comp_annotation",
    "rcsb_chem_comp_related",
    "rcsb_entry_group_membership",
    "rcsb_ihm_dataset_source_db_reference",
    "rcsb_ma_qa_metric_global.ma_qa_metric_global",
    "rcsb_membrane_lineage",
    "rcsb_nonpolymer_entity_annotation",
    "rcsb_nonpolymer_entity_annotation.annotation_lineage",
    "rcsb_nonpolymer_entity_feature_summary",
    "rcsb_nonpolymer_instance_annotation",
    "rcsb_nonpolymer_instance_annotation.annotation_lineage",
    "rcsb_polymer_entity.rcsb_ec_lineage",
    "rcsb_polymer_entity.rcsb_enzyme_class_combined",
    "rcsb_polymer_entity_annotation",
    "rcsb_polymer_entity_annotation.annotation_lineage",
    "rcsb_polymer_entity_container_identifiers.reference_sequence_identifiers",
    "rcsb_polymer_entity_feature_summary",
    "rcsb_polymer_entity_group_membership",
    "rcsb_polymer_instance_annotation",
    "rcsb_polymer_instance_annotation.annotation_lineage",
    "rcsb_polymer_instance_feature_summary",
    "rcsb_pubmed_mesh_descriptors_lineage",
    "rcsb_struct_symmetry",
    "rcsb_struct_symmetry_lineage",
    "rcsb_uniprot_annotation",
    "rcsb_uniprot_annotation.annotation_lineage",
    "rcsb_uniprot_container_identifiers.reference_sequence_identifiers"
]

# chemical: 16 roots covering 57 attributes.
CHEMICAL_ATTRIBUTE_SCOPES: dict[str, AttributeScope] = {
    "chem_comp": "mol_definition",
    "drugbank_container_identifiers": "mol_definition",
    "drugbank_info": "mol_definition",
    "drugbank_target": "mol_definition",
    "pdbx_reference_molecule": "mol_definition",
    "pdbx_reference_molecule_family": "mol_definition",
    "pdbx_reference_molecule_related_structures": "mol_definition",
    "pdbx_reference_molecule_synonyms": "mol_definition",
    "rcsb_chem_comp_annotation": "mol_definition",
    "rcsb_chem_comp_container_identifiers": "mol_definition",
    "rcsb_chem_comp_descriptor": "mol_definition",
    "rcsb_chem_comp_info": "mol_definition",
    "rcsb_chem_comp_related": "mol_definition",
    "rcsb_chem_comp_synonyms": "mol_definition",
    "rcsb_chem_comp_target": "mol_definition",
    "rcsb_id": "mol_definition"
}

# Attributes filed under a finer root whose VALUE is the parent entry's id, so it
# is identical across every sibling and two conditions on it can never be met by
# different siblings. `queries.scope_of` returns "entry" for these.
CHEMICAL_ATTRIBUTE_ENTRY_CONSTANT: list[str] = []

# Roots holding MANY records per object (7 of 16).
# Two conditions on one of these can land on DIFFERENT records of the SAME object, so
# scope equality does not mean the conditions co-occur — software.name and
# software.classification are both entry-scoped, yet 18 of 25 sampled hits for
# AND(name~PHENIX, classification~'data reduction') have no single record with both.
CHEMICAL_ATTRIBUTE_REPEATING_ROOTS: list[str] = [
    "drugbank_target",
    "pdbx_reference_molecule_related_structures",
    "pdbx_reference_molecule_synonyms",
    "rcsb_chem_comp_annotation",
    "rcsb_chem_comp_related",
    "rcsb_chem_comp_synonyms",
    "rcsb_chem_comp_target"
]

# The PATHS the Search API nested-indexes (3): it tracks the record, so
# conditions kept together in their OWN group are required to hold on one record.
# That makes these fixable at the query level; the rest of the repeating roots are not.
# Paths, not roots: the flag sits on the coherent sub-object, which for 6 roots is a
# descendant (rcsb_uniprot_container_identifiers.reference_sequence_identifiers, ...),
# so an attribute is coherent-able only when it sits UNDER one of these prefixes.
CHEMICAL_ATTRIBUTE_NESTED_ROOTS: list[str] = [
    "drugbank_info.drug_products",
    "rcsb_chem_comp_annotation",
    "rcsb_chem_comp_related"
]
