"""Searchable RCSB **chemical** (text_chem) attributes.

Auto-generated by scripts/generate_search_attributes.py from
https://search.rcsb.org/rcsbsearch/v2/metadata/chemical/schema
Do not edit by hand; re-run the generator to refresh.
"""

from rcsb_mcp.attribute_types import SearchAttribute

CHEMICAL_SEARCH_ATTRIBUTES: list[SearchAttribute] = [
    {
        "attribute": "chem_comp.formula_weight",
        "type": "number",
        "operators": [
            "equals",
            "greater",
            "in",
            "less",
            "greater_or_equal",
            "less_or_equal",
            "range",
            "exists"
        ],
        "description": "Formula mass of the chemical component."
    },
    {
        "attribute": "chem_comp.name",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The full name of the component."
    },
    {
        "attribute": "chem_comp.type",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "For standard polymer components, the type of the monomer. Note that monomers that will form polymers are of three types: linking monomers, monomers with some type of N-terminal (or 5') cap and monomers with some type of C-terminal (or 3') cap.",
        "enum": [
            "D-beta-peptide, C-gamma linking",
            "D-gamma-peptide, C-delta linking",
            "D-peptide COOH carboxy terminus",
            "D-peptide NH3 amino terminus",
            "D-peptide linking",
            "D-saccharide",
            "D-saccharide, alpha linking",
            "D-saccharide, beta linking",
            "DNA OH 3 prime terminus",
            "DNA OH 5 prime terminus",
            "DNA linking",
            "L-DNA linking",
            "L-RNA linking",
            "L-beta-peptide, C-gamma linking",
            "L-gamma-peptide, C-delta linking",
            "L-peptide COOH carboxy terminus",
            "L-peptide NH3 amino terminus",
            "L-peptide linking",
            "L-saccharide",
            "L-saccharide, alpha linking",
            "L-saccharide, beta linking",
            "RNA OH 3 prime terminus",
            "RNA OH 5 prime terminus",
            "RNA linking",
            "non-polymer",
            "other",
            "peptide linking",
            "peptide-like",
            "saccharide"
        ]
    },
    {
        "attribute": "drugbank_container_identifiers.drugbank_id",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "The DrugBank accession code"
    },
    {
        "attribute": "drugbank_info.affected_organisms",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The DrugBank drug affected organisms."
    },
    {
        "attribute": "drugbank_info.atc_codes",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "The Anatomical Therapeutic Chemical Classification System (ATC) codes."
    },
    {
        "attribute": "drugbank_info.brand_names",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "DrugBank drug brand names."
    },
    {
        "attribute": "drugbank_info.cas_number",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "The DrugBank assigned Chemical Abstracts Service identifier."
    },
    {
        "attribute": "drugbank_info.description",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The DrugBank drug description."
    },
    {
        "attribute": "drugbank_info.drug_categories",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The DrugBank drug categories."
    },
    {
        "attribute": "drugbank_info.drug_groups",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "The DrugBank drug groups determine their drug development status.",
        "enum": [
            "approved",
            "experimental",
            "illicit",
            "investigational",
            "nutraceutical",
            "vet_approved",
            "withdrawn"
        ]
    },
    {
        "attribute": "drugbank_info.drug_products.approved",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "Indicates whether this drug has been approved by the regulating government.",
        "enum": [
            "N",
            "Y"
        ]
    },
    {
        "attribute": "drugbank_info.drug_products.country",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "The country where this commercially available drug has been approved.",
        "enum": [
            "Canada",
            "EU",
            "US"
        ]
    },
    {
        "attribute": "drugbank_info.drug_products.ended_marketing_on",
        "type": "date",
        "operators": [
            "equals",
            "greater",
            "in",
            "less",
            "greater_or_equal",
            "less_or_equal",
            "range",
            "exists"
        ],
        "description": "The ending date for market approval."
    },
    {
        "attribute": "drugbank_info.drug_products.started_marketing_on",
        "type": "date",
        "operators": [
            "equals",
            "greater",
            "in",
            "less",
            "greater_or_equal",
            "less_or_equal",
            "range",
            "exists"
        ],
        "description": "The starting date for market approval."
    },
    {
        "attribute": "drugbank_info.indication",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The DrugBank drug indication."
    },
    {
        "attribute": "drugbank_info.mechanism_of_action",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The DrugBank drug mechanism of actions."
    },
    {
        "attribute": "drugbank_info.name",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The DrugBank drug name."
    },
    {
        "attribute": "drugbank_info.pharmacology",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The DrugBank drug pharmacology."
    },
    {
        "attribute": "drugbank_info.synonyms",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "DrugBank drug name synonyms."
    },
    {
        "attribute": "drugbank_target.interaction_type",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The type of target interaction."
    },
    {
        "attribute": "drugbank_target.name",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The target name."
    },
    {
        "attribute": "drugbank_target.organism_common_name",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The organism common name."
    },
    {
        "attribute": "drugbank_target.target_actions",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The actions of the target interaction."
    },
    {
        "attribute": "pdbx_reference_molecule.class",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "Broadly defines the function of the entity.",
        "enum": [
            "Antagonist",
            "Anthelmintic",
            "Antibiotic",
            "Antibiotic, Anthelmintic",
            "Antibiotic, Antimicrobial",
            "Antibiotic, Antineoplastic",
            "Anticancer",
            "Anticoagulant",
            "Anticoagulant, Antithrombotic",
            "Antifungal",
            "Antigen",
            "Antiinflammatory",
            "Antimicrobial",
            "Antimicrobial, Antiparasitic, Antibiotic",
            "Antimicrobial, Antiretroviral",
            "Antimicrobial, Antitumor",
            "Antineoplastic",
            "Antiparasitic",
            "Antiretroviral",
            "Antithrombotic",
            "Antitumor",
            "Antiviral",
            "CASPASE inhibitor",
            "Chaperone binding",
            "Drug delivery",
            "Enzyme inhibitor",
            "Glycan component",
            "Growth factor",
            "Immunosuppressant",
            "Inducer",
            "Inhibitor",
            "Lantibiotic",
            "Metabolism",
            "Metal transport",
            "Nutrient",
            "Oxidation-reduction",
            "Protein binding",
            "Receptor",
            "Substrate analog",
            "Synthetic opioid",
            "Thrombin inhibitor",
            "Thrombin inhibitor, Trypsin inhibitor",
            "Toxin",
            "Transition state mimetic",
            "Transport activator",
            "Trypsin inhibitor",
            "Unknown",
            "Water retention"
        ]
    },
    {
        "attribute": "pdbx_reference_molecule.description",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "Description of this molecule."
    },
    {
        "attribute": "pdbx_reference_molecule.name",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "A name of the entity."
    },
    {
        "attribute": "pdbx_reference_molecule.prd_id",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "The value of _pdbx_reference_molecule.prd_id is the unique identifier for the reference molecule in this family. By convention this ID uniquely identifies the reference molecule in in the PDB reference dictionary. The ID has the template form PRD_dddddd (e.g. PRD_000001)"
    },
    {
        "attribute": "pdbx_reference_molecule.type",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "Defines the structural classification of the entity.",
        "enum": [
            "Amino acid",
            "Aminoglycoside",
            "Ansamycin",
            "Anthracycline",
            "Anthraquinone",
            "Chalkophore",
            "Chalkophore, Polypeptide",
            "Chromophore",
            "Cyclic depsipeptide",
            "Cyclic lipopeptide",
            "Cyclic peptide",
            "Glycopeptide",
            "Heterocyclic",
            "Imino sugar",
            "Keto acid",
            "Lipoglycopeptide",
            "Lipopeptide",
            "Macrolide",
            "Non-polymer",
            "Nucleoside",
            "Oligopeptide",
            "Oligosaccharide",
            "Peptaibol",
            "Peptide-like",
            "Polycyclic",
            "Polypeptide",
            "Polysaccharide",
            "Quinolone",
            "Siderophore",
            "Thiolactone",
            "Thiopeptide",
            "Unknown"
        ]
    },
    {
        "attribute": "pdbx_reference_molecule_family.name",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The entity family name."
    },
    {
        "attribute": "pdbx_reference_molecule_related_structures.db_code",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The database identifier code for the related structure reference."
    },
    {
        "attribute": "pdbx_reference_molecule_synonyms.name",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "A synonym name for the entity."
    },
    {
        "attribute": "rcsb_chem_comp_annotation.annotation_id",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "An identifier for the annotation."
    },
    {
        "attribute": "rcsb_chem_comp_annotation.annotation_lineage.depth",
        "type": "integer",
        "operators": [
            "equals",
            "greater",
            "in",
            "less",
            "greater_or_equal",
            "less_or_equal",
            "range",
            "exists"
        ],
        "description": "Members of the annotation lineage as parent lineage depth (1-N)"
    },
    {
        "attribute": "rcsb_chem_comp_annotation.annotation_lineage.id",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "Members of the annotation lineage as parent class identifiers."
    },
    {
        "attribute": "rcsb_chem_comp_annotation.annotation_lineage.name",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "Members of the annotation lineage as parent class names."
    },
    {
        "attribute": "rcsb_chem_comp_annotation.description",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "A description for the annotation."
    },
    {
        "attribute": "rcsb_chem_comp_annotation.name",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "A name for the annotation."
    },
    {
        "attribute": "rcsb_chem_comp_annotation.type",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "A type or category of the annotation.",
        "enum": [
            "ATC",
            "Carbohydrate Anomer",
            "Carbohydrate Isomer",
            "Carbohydrate Primary Carbonyl Group",
            "Carbohydrate Ring",
            "Generating Enzyme",
            "Modification Type",
            "PSI-MOD"
        ]
    },
    {
        "attribute": "rcsb_chem_comp_container_identifiers.comp_id",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "The chemical component identifier."
    },
    {
        "attribute": "rcsb_chem_comp_container_identifiers.drugbank_id",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "The DrugBank identifier corresponding to the chemical component."
    },
    {
        "attribute": "rcsb_chem_comp_container_identifiers.prd_id",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "The BIRD definition identifier."
    },
    {
        "attribute": "rcsb_chem_comp_container_identifiers.rcsb_id",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "A unique identifier for the chemical definition in this container."
    },
    {
        "attribute": "rcsb_chem_comp_descriptor.InChIKey",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "Standard IUPAC International Chemical Identifier (InChI) descriptor key for the chemical component InChI, the IUPAC International Chemical Identifier, by Stephen R Heller, Alan McNaught, Igor Pletnev, Stephen Stein and Dmitrii Tchekhovskoi, Journal of Cheminformatics, 2015, 7:23"
    },
    {
        "attribute": "rcsb_chem_comp_info.atom_count_chiral",
        "type": "integer",
        "operators": [
            "equals",
            "greater",
            "in",
            "less",
            "greater_or_equal",
            "less_or_equal",
            "range",
            "exists"
        ],
        "description": "Chemical component chiral atom count"
    },
    {
        "attribute": "rcsb_chem_comp_info.atom_count_heavy",
        "type": "integer",
        "operators": [
            "equals",
            "greater",
            "in",
            "less",
            "greater_or_equal",
            "less_or_equal",
            "range",
            "exists"
        ],
        "description": "Chemical component heavy atom count"
    },
    {
        "attribute": "rcsb_chem_comp_info.bond_count",
        "type": "integer",
        "operators": [
            "equals",
            "greater",
            "in",
            "less",
            "greater_or_equal",
            "less_or_equal",
            "range",
            "exists"
        ],
        "description": "Chemical component total bond count"
    },
    {
        "attribute": "rcsb_chem_comp_info.bond_count_aromatic",
        "type": "integer",
        "operators": [
            "equals",
            "greater",
            "in",
            "less",
            "greater_or_equal",
            "less_or_equal",
            "range",
            "exists"
        ],
        "description": "Chemical component aromatic bond count"
    },
    {
        "attribute": "rcsb_chem_comp_info.initial_deposition_date",
        "type": "date",
        "operators": [
            "equals",
            "greater",
            "in",
            "less",
            "greater_or_equal",
            "less_or_equal",
            "range",
            "exists"
        ],
        "description": "The date the chemical definition was first deposited in the PDB repository."
    },
    {
        "attribute": "rcsb_chem_comp_info.initial_release_date",
        "type": "date",
        "operators": [
            "equals",
            "greater",
            "in",
            "less",
            "greater_or_equal",
            "less_or_equal",
            "range",
            "exists"
        ],
        "description": "The initial date the chemical definition was released in the PDB repository."
    },
    {
        "attribute": "rcsb_chem_comp_related.resource_accession_code",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "The resource identifier code for the related chemical reference."
    },
    {
        "attribute": "rcsb_chem_comp_related.resource_name",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "The resource name for the related chemical reference.",
        "enum": [
            "CAS",
            "CCDC/CSD",
            "COD",
            "ChEBI",
            "ChEMBL",
            "DrugBank",
            "Pharos",
            "PubChem",
            "RESID"
        ]
    },
    {
        "attribute": "rcsb_chem_comp_synonyms.name",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The synonym of this particular chemical component."
    },
    {
        "attribute": "rcsb_chem_comp_synonyms.provenance_source",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "The provenance of this synonym.",
        "enum": [
            "ACDLabs",
            "Author",
            "ChEBI",
            "ChEMBL",
            "DrugBank",
            "GMML",
            "Lexichem",
            "OpenEye OEToolkits",
            "OpenEye/Lexichem",
            "PDB Reference Data",
            "PDB Reference Data (Preferred)",
            "PDB-CARE",
            "PubChem",
            "RESID"
        ]
    },
    {
        "attribute": "rcsb_chem_comp_synonyms.type",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "This data item contains the synonym type.",
        "enum": [
            "Brand Name",
            "Common Name",
            "Condensed IUPAC Carbohydrate Symbol",
            "IUPAC Carbohydrate Symbol",
            "Preferred Common Name",
            "Preferred Name",
            "Preferred Synonym",
            "SNFG Carbohydrate Symbol",
            "Synonym",
            "Systematic Name"
        ]
    },
    {
        "attribute": "rcsb_chem_comp_target.name",
        "type": "string",
        "operators": [
            "contains_phrase",
            "contains_words",
            "exists"
        ],
        "description": "The chemical component target name."
    },
    {
        "attribute": "rcsb_id",
        "type": "string",
        "operators": [
            "in",
            "exact_match",
            "exists"
        ],
        "description": "A unique identifier for the chemical definition in this container."
    }
]
