"""Shared tool-definition helpers — the bits every tool group needs to declare a tool.

Distinct from :mod:`rcsb_mcp.client` (network transport): this holds the pieces that
describe a tool to MCP, not the pieces that make an HTTP call. Kept here so a tool
package can ``register_<x>_tools(mcp)`` without importing :mod:`rcsb_mcp.server` — the
dependency runs one way, tool modules import this, never the reverse, so no cycles.

Only genuinely cross-cutting tool-definition bits belong here (used by 2+ tool groups).
A helper specific to one domain stays with that domain's package.
"""

from __future__ import annotations

from typing import Any

from mcp.types import ToolAnnotations

# Every tool in this server is a read-only query against public RCSB/EBI web
# APIs: it never mutates state, repeated calls are safe (idempotent), and it
# reaches external services (open world). Shared by all @mcp.tool decorators.
READ_ONLY = ToolAnnotations(
    readOnlyHint=True,
    destructiveHint=False,
    idempotentHint=True,
    openWorldHint=True,
)


# --- JSON-Schema compaction ---------------------------------------------------
# Every tool schema is generated by pydantic from the function signature, and
# pydantic emits three keywords that cost tokens in every request and carry no
# information the model doesn't already have from the key beside them. Measured
# across the 36 registered tools: 3,413 tokens, 25% of the whole JSON surface.
#
# All three are removable WITHOUT changing what validates: `title` and `default`
# are annotation-only keywords in JSON Schema (they never decide whether an
# instance is valid), and `additionalProperties: true` is the spec default. The
# predicates are separate so each can be reverted on its own.


def _drop_title(key: str, value: Any) -> bool:
    """`title` — pydantic derives it from the key it sits next to.

    236 of the 285 are the field name title-cased (``query`` -> ``"Query"``); the
    rest are the model class or tool name, already carried by the ``$defs`` key or
    the tool's own name. Nothing here is information. Note this is the SCHEMA's
    title, not ``Tool.title`` — the human-facing tool name is a separate field and
    is untouched.
    """
    return key == "title"


def _drop_null_default(key: str, value: Any) -> bool:
    """``"default": null`` — redundant with the field's absence from ``required``.

    Every field carrying it has a Python default of ``None``, so an omitted
    argument and an explicit ``null`` bind identically; no tool can tell them apart
    (none takes ``**kwargs`` or a Context, so none ever sees raw arguments). NOTE
    the null check: non-null defaults (``limit=10``, ``return_type="entry"``) are
    load-bearing — the model reads them to know what it gets when it omits the
    argument — and MUST survive.
    """
    return key == "default" and value is None


def _drop_redundant_additional_properties(key: str, value: Any) -> bool:
    """``"additionalProperties": true`` — restating the JSON Schema default.

    Only ``true`` goes. The ``false`` occurrences are a real constraint (they close
    the object) and are kept.
    """
    return key == "additionalProperties" and value is True


SCHEMA_NOISE = (_drop_title, _drop_null_default, _drop_redundant_additional_properties)

# Keywords whose keys are NAMES the author chose, not schema keywords. A naive
# "drop every key called title" walk cannot tell `{"title": "Query"}` (pydantic
# noise) from `{"properties": {"title": {...}}}` (rcsb_render_report's page-heading
# field, which is also in `required`) — and deleting the latter leaves a required
# property with no definition. So descend into these maps by VALUE only.
_NAME_MAPS = ("properties", "$defs", "definitions", "patternProperties", "dependentSchemas")


def _compact(node: Any) -> Any:
    """Recursively rebuild `node` without the keys every SCHEMA_NOISE predicate rejects."""
    if isinstance(node, dict):
        out: dict[str, Any] = {}
        for k, v in node.items():
            if k in _NAME_MAPS and isinstance(v, dict):
                # Author-chosen names: keep every key, compact each value as a schema.
                out[k] = {name: _compact(subschema) for name, subschema in v.items()}
            elif not any(drop(k, v) for drop in SCHEMA_NOISE):
                out[k] = _compact(v)
        return out
    if isinstance(node, list):
        return [_compact(v) for v in node]
    return node


def compact_tool_schemas(mcp: Any) -> None:
    """Strip token-only noise from every registered tool's input and output schema.

    Call ONCE from the composition root, after every ``register_*_tools(mcp)`` —
    doing it centrally is why no tool module has to know this happens. Both
    ``Tool.parameters`` and ``fn_metadata.output_schema`` are plain dicts that
    ``list_tools`` serves as-is rather than re-deriving, so mutating them here is
    what the client actually receives.
    """
    for tool in mcp._tool_manager.list_tools():
        tool.parameters = _compact(tool.parameters)
        output_schema = getattr(tool.fn_metadata, "output_schema", None)
        if output_schema is not None:
            tool.fn_metadata.output_schema = _compact(output_schema)
